"""Initial migration

Revision ID: 5ae2b4a26277
Revises: 
Create Date: 2026-03-27 16:42:43.372380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5ae2b4a26277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_response_text', sa.Text(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_analyses_analysis_id'), 'claim_analyses', ['analysis_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_conversation_id'), 'documents', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_result_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_embedding'), 'document_chunks', ['embedding'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('nli_entailment_prob', sa.Float(), nullable=False),
    sa.Column('nli_contradiction_prob', sa.Float(), nullable=False),
    sa.Column('nli_neutral_prob', sa.Float(), nullable=False),
    sa.Column('nli_verdict', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['claim_analysis_id'], ['claim_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_claim_analysis_id'), 'evidence_items', ['claim_analysis_id'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_entities_conversation_id'), 'extracted_entities', ['conversation_id'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=255), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['extracted_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['extracted_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_conversation_id'), 'entity_relationships', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_relationships_conversation_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_extracted_entities_conversation_id'), table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index(op.f('ix_evidence_items_claim_analysis_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_document_chunks_embedding'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_documents_conversation_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_claim_analyses_analysis_id'), table_name='claim_analyses')
    op.drop_table('claim_analyses')
    op.drop_table('conversations')
    op.drop_table('analysis_results')
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
