"""v2_pipeline_schema

Revision ID: 88ea57705806
Revises: 001_initial_schema
Create Date: 2026-04-07 00:53:06.922603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ea57705806'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_analyses', sa.Column('domain', sa.String(length=50), nullable=True))
    op.add_column('claim_analyses', sa.Column('exact_quote', sa.Text(), nullable=True))
    op.add_column('claim_analyses', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('claim_analyses', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('claim_analyses', sa.Column('suggestion', sa.Text(), nullable=True))
    op.add_column('evidence_items', sa.Column('source_tier', sa.String(length=20), nullable=True))
    op.add_column('extracted_entities', sa.Column('message_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_entities', 'message_index')
    op.drop_column('evidence_items', 'source_tier')
    op.drop_column('claim_analyses', 'suggestion')
    op.drop_column('claim_analyses', 'reasoning')
    op.drop_column('claim_analyses', 'confidence')
    op.drop_column('claim_analyses', 'exact_quote')
    op.drop_column('claim_analyses', 'domain')
    # ### end Alembic commands ###
